### ISSUE TITLE
Issues running primegen example

### ISSUE THREAD

**Issue by stefdoerr** [GoogleCloudPlatform/batch-samples#22]
Hi, I have managed to execute the primegen example on a new project. However I'm consistently getting the following error after running `test.sh`:

```yaml
argument: 'null'
endTime: '2022-10-07T12:03:18.398420219Z'
error:
  context: |-
    HTTP server responded with error code 403
    in step "createAndRunBatchJob", routine "main", line: 43
  payload: '{"body":{"error":{"code":403,"message":"caller does not have access to
    act as the specified service account: \"38845042110-compute@developer.gserviceaccount.com\"","status":"PERMISSION_DENIED"}},"code":403,"headers":{"Alt-Svc":"h3=\":443\";
    ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\";
    ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","Cache-Control":"private","Content-Length":"213","Content-Type":"application/json;
    charset=UTF-8","Date":"Fri, 07 Oct 2022 12:03:18 GMT","Server":"ESF","Vary":"Origin","X-Content-Type-Options":"nosniff","X-Frame-Options":"SAMEORIGIN","X-Xss-Protection":"0"},"message":"HTTP
    server responded with error code 403","tags":["HttpError"]}'
  stackTrace:
    elements:
    - position:
        column: '9'
        length: '4'
        line: '43'
      routine: main
      step: createAndRunBatchJob
name: projects/XXXXX/locations/us-central1/workflows/batch-primegen2/executions/YYYYYYYY-47d1-bb28-5e8d53650932
startTime: '2022-10-07T12:03:16.814130268Z'
state: FAILED
status:
  currentSteps:
  - routine: main
    step: createAndRunBatchJob
workflowRevisionId: 000001-77d
```

I tried to debug this a bit, it seems like when enabling the services some new service accounts are generated (in this case `38845042110-compute@developer.gserviceaccount.com`) and for some reason the service account running the workflow (here: `workflows-batch-sa`) tries to use the other service account to create the batch job and fails.

What's even weirder is that I tried to also give `workflows-batch-sa` role as service-account manager so that it has access on the `38845..` account yet it still gives me the same error. 

Could you help me out? I'm a bit lost here given that the example doesn't work.
