### ISSUE TITLE
Script and Container jobs failing with: The resource 'projects/<ProjectNumber>/global/networks/default' was not found

### ISSUE THREAD

**Issue by rmharrison** [GoogleCloudPlatform/batch-samples#27]
I ran both [busybox](https://github.com/GoogleCloudPlatform/batch-samples/tree/main/busybox) (Container Job) and [transcoding](https://github.com/GoogleCloudPlatform/batch-samples/tree/main/transcoding) (Script Job). Using both the sample scripts and web console.

This error does not exist in [Troubleshooting](https://cloud.google.com/batch/docs/troubleshooting).

My best guess...
1. Batch assumes the default network
2. I don't have a default network set

**==> How do I set my default network?**
I have an existing network interface that I've used without incident for a manually provisioned Compute Engine VM instance.

### Busybox, Script
```
# gcloud beta batch jobs describe job-busybox-9172 --location=us-central1
...
status:
  runDuration: 0s
  state: FAILED
  statusEvents:
  - description: Job state is set from QUEUED to SCHEDULED for job projects/<ProjectNumber>/locations/us-central1/jobs/job-busybox-9172.
    eventTime: '2023-03-07T22:04:48.589892441Z'
    type: STATUS_CHANGED
  - description: "Job gets no longer retryable information Batch Error: code - CODE_GCE_RESOURCE_NOT_FOUND,\
      \ description - googleapi: Error 404: The resource 'projects/<ProjectNumber>/global/networks/default'\
      \ was not found, notFound, already retried 3 times, errors record CODE_GCE_RESOURCE_NOT_FOUND."
    eventTime: '2023-03-07T22:08:21.906612928Z'
    type: OPERATIONAL_INFO
  - description: Job state is set from SCHEDULED to SCHEDULED_PENDING_FAILED for job
      projects/<ProjectNumber>/locations/us-central1/jobs/job-busybox-9172.
    eventTime: '2023-03-07T22:08:22.671616487Z'
    type: STATUS_CHANGED
  - description: Job state is set from SCHEDULED_PENDING_FAILED to FAILED for job
      projects/<ProjectNumber>/locations/us-central1/jobs/job-busybox-9172.
    eventTime: '2023-03-07T22:08:23.845508708Z'
    type: STATUS_CHANGED
```

### Transcoding, Web Console
```
# gcloud beta batch jobs describe transcode-manual --location=us-central1
...
status:
  runDuration: 0s
  state: FAILED
  statusEvents:
  - description: Job state is set from QUEUED to SCHEDULED for job projects/<ProjectNumber>/locations/us-central1/jobs/transcode-manual.
    eventTime: '2023-03-07T21:55:45.825619439Z'
    type: STATUS_CHANGED
  - description: "Job gets no longer retryable information Batch Error: code - CODE_GCE_RESOURCE_NOT_FOUND,\
      \ description - googleapi: Error 404: The resource 'projects/<ProjectNumber>/global/networks/default'\
      \ was not found, notFound, already retried 3 times, errors record CODE_GCE_RESOURCE_NOT_FOUND."
    eventTime: '2023-03-07T21:59:22.741203703Z'
    type: OPERATIONAL_INFO
  - description: Job state is set from SCHEDULED to SCHEDULED_PENDING_FAILED for job
      projects/<ProjectNumber>/locations/us-central1/jobs/transcode-manual.
    eventTime: '2023-03-07T21:59:23.388154925Z'
    type: STATUS_CHANGED
  - description: Job state is set from SCHEDULED_PENDING_FAILED to FAILED for job
      projects/<ProjectNumber>/locations/us-central1/jobs/transcode-manual.
    eventTime: '2023-03-07T21:59:24.291823883Z'
    type: STATUS_CHANGED
```
